#include <stdlib.h>

struct ListNode
{
    int val;
    struct ListNode *next;
};

struct ListNode *swapPairs(struct ListNode *head)
{
    struct ListNode *dummy = (struct ListNode *)malloc(sizeof(struct ListNode));
    dummy->next = head;
    struct ListNode *pre = dummy;
    struct ListNode *cur = head;
    while (cur != NULL && cur->next != NULL)
    {
        pre->next = cur->next;
        struct ListNode *tmp = cur->next->next;
        cur->next->next = cur;
        cur->next = tmp;
        pre = cur;
        cur = cur->next;
    }
    return dummy->next;
}

// Yet another solution, generated by Copilot
struct ListNode *swapPairs2(struct ListNode *head)
{
    if (head == NULL || head->next == NULL)
        return head;

    struct ListNode *dummy = (struct ListNode *)malloc(sizeof(struct ListNode));
    dummy->next = head;
    struct ListNode *prev = dummy;
    struct ListNode *curr = head;

    while (curr != NULL && curr->next != NULL)
    {
        struct ListNode *next = curr->next;
        prev->next = next;
        curr->next = next->next;
        next->next = curr;

        prev = curr;
        curr = curr->next;
    }

    return dummy->next;
}